### ISSUE TITLE
BetterNether (And if I am correct BetterEnd as well) are incompatible with Hydrogen

### ISSUE THREAD

**Issue by Kizuati** [CaffeineMC/hydrogen-fabric#15] opened 2021-01-18 20:44 UTC
[latest.log](https://github.com/jellysquid3/hydrogen-fabric/files/5832318/latest.log)
Crash log with latest release here,generation works fine without it. I talked a bit more about it in the [BetterNether issues](https://github.com/paulevsGitch/BetterNether/issues/281) mentioning another crash with an older version of Hydrogen (from Discord).

**Comment by Kroppeb** [comment] 2021-01-18 20:55
Hydrogen seems to be removing the `bottom` property of the `golden_vine` block.

**Comment by Dolphin2Point1** [comment] 2021-01-20 03:48
duplicate of #10

**Closed as completed** 2021-01-22 15:04 UTC
