### ISSUE TITLE
Bug... Oftifabric + hydrogen mod

### ISSUE THREAD

**Issue by SevenIsNotNumber** [CaffeineMC/hydrogen-fabric#29] opened 2021-03-02 01:49 UTC
After loading is completed, minecraft will load, then it will go back to splash screen again...

**Comment by LucilleTea** [comment] 2021-03-02 01:52
Duplicate of #20

**Closed as completed by LucilleTea** 2021-03-02 01:52 UTC
Labels: duplicate

**Comment by SevenIsNotNumber** [comment] 2021-03-02 01:53
> Duplicate of #20


Logs https://pastebin.pl/view/8c7ad6cd

**Comment by SevenIsNotNumber** [comment] 2021-03-02 01:54
I use a minecraft java launcher for android....

**Comment by SevenIsNotNumber** [comment] 2021-03-02 01:54
Btw thanks for respond
