### ISSUE TITLE
Incompatible with Optifine G6

### ISSUE THREAD

**Issue by MeeniMc** [CaffeineMC/hydrogen-fabric#20] opened 2021-02-03 08:24 UTC
I understand it is probably not high on the priority list, but here is the bug report anyway, if it happens to be an easy fix. There is the possibility that other mods use the method as well and would suffer from the same bug then.

```
Caused by: java.lang.UnsupportedOperationException
	at me.jellysquid.mods.hydrogen.common.collections.FixedArrayList.clear(FixedArrayList.java:106) ~[hydrogen-fabric-mc1.16.5-0.2.jar:?]
	at net.optifine.model.BlockModelUtils.replaceTexture(BlockModelUtils.java:178) ~[Optifine-mapped.jar:?]
	at net.optifine.model.BlockModelUtils.makeModel(BlockModelUtils.java:152) ~[Optifine-mapped.jar:?]
	at net.optifine.BetterGrass.update(BetterGrass.java:99) ~[Optifine-mapped.jar:?]
	at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:315) ~[Optifine-mapped.jar:?]
	at net.optifine.util.TextureUtils$2.method_14491(TextureUtils.java:393) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
	... 193 more
```

**Comment by amnotbananaama** [comment] 2021-02-04 03:59
Looks like [Hydrogen's implimentation of clear()](https://github.com/CaffeineMC/hydrogen-fabric/blob/1.16.x/src/main/java/me/jellysquid/mods/hydrogen/common/collections/FixedArrayList.java#L105L108) throws this directly. I'm not sure if this is unavoidable, or if that is placeholder code that was intended to be replaced later. My guess is the former given how many other neighboring methods also throw exceptions.

**Comment by campbebj** [comment] 2021-02-12 17:33
+1 to this bug

**Comment by timelady-victorious** [comment] 2021-02-17 12:40
+1 to this bug. But also I doubt it will be fixed because Hydrogen is part of the fabric altertatives (caffeinMC) and optifine is hard to be compatiable with.

**Comment by arjunindia** [comment] 2021-02-20 19:53
also check G7, out now

**Comment by campbebj** [comment] 2021-02-20 20:11
G7 doesnt have fabric support through optifabric yet (i tried it and all the UI disappears)

**Comment by ghost** [comment] 2021-04-25 08:00
+1

**Comment by jellysquid3** [comment] 2021-04-25 22:45
OptiFine is not supported, and this will very likely never change. It's too much of a moving target and the lengths we have to go through to debug and workaround issues they create is not worthwhile. The issue here looks to be that OptiFine is messing around with block models after they've been loaded (which seems like a violation of contract here given this data should be immutable) and this causes Hydrogen to throw an error.

Also, please don't comment with +1 and such. This generates an email for every subscribed participant to the thread and creates spam in our inboxes for no good reason. Use emoji reactions if you want to show support for something.

**Closed as completed by jellysquid3** 2021-04-25 22:45 UTC
