### ISSUE TITLE
Game stuck loading

### ISSUE THREAD

**Issue by Minionguyjpro** [CaffeineMC/hydrogen-fabric#43] opened 2021-06-19 15:22 UTC
Using Hydrogen by me let the game being stuck on loading.
Im using:
OS: Windows 10
Java/JDK: Adoptopenjdk 16.0.1
Minecraft: 1.17

**Comment by MeeniMc** [comment] 2021-06-21 04:24
Are you using Optifine/optifabric by any chance? 

Hydrogen is incompatible with Optifine.

**Comment by Minionguyjpro** [comment] 2021-06-21 12:55
Yeah that right, but why doesnt it work?

**Comment by amnotbananaama** [comment] 2021-06-21 18:46
Closing as a duplicate of #20. See there:
> The issue here looks to be that OptiFine is messing around with block models after they've been loaded (which seems like a violation of contract here given this data should be immutable) and this causes Hydrogen to throw an error.

**Closed as completed by amnotbananaama** 2021-06-21 18:46 UTC
Labels: duplicate
